# Generated by Django 4.1.13 on 2025-01-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_no', models.CharField(blank=True, max_length=50, null=True)),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('citizen_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('citizen_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('pack', models.IntegerField()),
                ('free', models.IntegerField(default=0)),
                ('purchase_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('purchase_cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=5, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventor_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
