# Generated by Django 4.1.13 on 2025-01-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
